// Code generated by MockGen. DO NOT EDIT.
// Source: internal/feature/tasks/service/service.go

// Package mock_tasks_service is a generated GoMock package.
package mock_tasks_service

import (
	context "context"
	reflect "reflect"

	domain "github.com/Akimpupupuu/ClearYourCity/task-service/internal/core/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTasksRepository is a mock of TasksRepository interface.
type MockTasksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTasksRepositoryMockRecorder
}

// MockTasksRepositoryMockRecorder is the mock recorder for MockTasksRepository.
type MockTasksRepositoryMockRecorder struct {
	mock *MockTasksRepository
}

// NewMockTasksRepository creates a new mock instance.
func NewMockTasksRepository(ctrl *gomock.Controller) *MockTasksRepository {
	mock := &MockTasksRepository{ctrl: ctrl}
	mock.recorder = &MockTasksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksRepository) EXPECT() *MockTasksRepositoryMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTasksRepository) CreateTask(ctx context.Context, task *domain.Task, token string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task, token)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTasksRepositoryMockRecorder) CreateTask(ctx, task, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksRepository)(nil).CreateTask), ctx, task, token)
}

// GetTask mocks base method.
func (m *MockTasksRepository) GetTask(ctx context.Context, taskID int) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, taskID)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTasksRepositoryMockRecorder) GetTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTasksRepository)(nil).GetTask), ctx, taskID)
}

// GetTasks mocks base method.
func (m *MockTasksRepository) GetTasks(ctx context.Context, userID, limit, offset int) ([]*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTasksRepositoryMockRecorder) GetTasks(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTasksRepository)(nil).GetTasks), ctx, userID, limit, offset)
}

// PatchStatus mocks base method.
func (m *MockTasksRepository) PatchStatus(ctx context.Context, task *domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchStatus", ctx, task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchStatus indicates an expected call of PatchStatus.
func (mr *MockTasksRepositoryMockRecorder) PatchStatus(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchStatus", reflect.TypeOf((*MockTasksRepository)(nil).PatchStatus), ctx, task)
}

// PatchTask mocks base method.
func (m *MockTasksRepository) PatchTask(ctx context.Context, task *domain.Task) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchTask", ctx, task)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchTask indicates an expected call of PatchTask.
func (mr *MockTasksRepositoryMockRecorder) PatchTask(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchTask", reflect.TypeOf((*MockTasksRepository)(nil).PatchTask), ctx, task)
}

// MockTasksRedis is a mock of TasksRedis interface.
type MockTasksRedis struct {
	ctrl     *gomock.Controller
	recorder *MockTasksRedisMockRecorder
}

// MockTasksRedisMockRecorder is the mock recorder for MockTasksRedis.
type MockTasksRedisMockRecorder struct {
	mock *MockTasksRedis
}

// NewMockTasksRedis creates a new mock instance.
func NewMockTasksRedis(ctrl *gomock.Controller) *MockTasksRedis {
	mock := &MockTasksRedis{ctrl: ctrl}
	mock.recorder = &MockTasksRedisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksRedis) EXPECT() *MockTasksRedisMockRecorder {
	return m.recorder
}

// DeleteRedis mocks base method.
func (m *MockTasksRedis) DeleteRedis(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRedis", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRedis indicates an expected call of DeleteRedis.
func (mr *MockTasksRedisMockRecorder) DeleteRedis(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRedis", reflect.TypeOf((*MockTasksRedis)(nil).DeleteRedis), ctx, token)
}

// GetAction mocks base method.
func (m *MockTasksRedis) GetAction(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAction", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAction indicates an expected call of GetAction.
func (mr *MockTasksRedisMockRecorder) GetAction(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAction", reflect.TypeOf((*MockTasksRedis)(nil).GetAction), ctx, token)
}

// ProlongAction mocks base method.
func (m *MockTasksRedis) ProlongAction(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProlongAction", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProlongAction indicates an expected call of ProlongAction.
func (mr *MockTasksRedisMockRecorder) ProlongAction(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProlongAction", reflect.TypeOf((*MockTasksRedis)(nil).ProlongAction), ctx, token)
}
